language: c++
dist: bionic
before_install:
- sudo apt-get update
- sudo apt-get install -y valgrind
script: make && make test && make valgrind
compiler:
- gcc
notifications:
  email:
    on_success: always
    on_failure: always
